config/routes.rb
Rails.application.routes.draw do
  resources :flats

  root to: 'flats#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    if params["/flats"].nil?
      @flats = Flat.all
    else
      @query = params["/flats"][:query]
      @flats = Flat.where(name: @query)
    end
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end


  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Simple Airbnb</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="ml-auto flex">
          <%= render 'search_form' %>

          <%= link_to "Add Flat", new_flat_path, class: "btn btn-outline-primary my-2 my-sm-0 ml-2"%>
        </div>
      </div>
</nav>

app/views/flats/_search_form.html.erb
<%= simple_form_for flats_path , method: 'get', class: 'form-control mr-sm-2' do |f| %>
    <%= f.input :query, class: 'btn btn-outline-success my-2 my-sm-0' %>
    <%= f.submit "Search" %>
<% end %>

app/views/flats/edit.html.erb
<h1>Edit page</h1>

app/views/flats/index.html.erb
  <div class="container">
    <div class="row">

      <% @flats.each do |flat| %>

      <div class="col-xs-4">
        <div class="flat-card">
          <div class="flat-card-image" style="background-image: url(<%= 'https://picsum.photos/350/180/?random&'+flat.name.delete(" ").delete("'") %>)"></div>
            <div class="flat-card-content">
              <div class="flat-card-title">
                <h4><%= link_to flat.name, flat_path(flat)%></h4>
              </div>
                <p>10 Clifton Gardens London W9 1DT</p>
                <div class="flex">
                  <div class="flex">
                    <i class="material-icons mr-2">people</i>
                    <span><%=flat.number_of_guests %></span>
                  </div>
                  <div class="flex ml-3">
                    <i class="material-icons mr-2">euro_symbol</i>
                    <%=flat.price_per_night %>
                  </div>
                </div>
            </div>
          <div class="flat-card-actions">
            <%= link_to "More info", flat_path(flat)%>
            <%= link_to "Edit", edit_flat_path(flat), class: "ml-3 text-warning"%>
            <%= link_to "Destroy", flat_path(flat), method: :delete, class: "ml-3 text-danger"%>
          </div>
        </div>
      </div>

      <% end %>
    </div>
  </div>

app/views/flats/new.html.erb
<h1>Flats#new</h1>
<p>Find me in app/views/flats/new.html.erb</p>

app/views/flats/show.html.erb
<div class="map" style="background-image: url(<%= 'https://picsum.photos/1440/350/?random&'+@flat.name.delete(" ").delete("'") %>)"></div>

<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card">
        <h1><%= @flat.name %></h1>
        <p class="flat-show-address"><%= @flat.address %></p>
      </div>
      <div class="flat-show-card">
        <h3>A bit more about this flat...</h3>
        <p><%= @flat.description %></p>
        <div class="map" style="background-image: url('https://maps.googleapis.com/maps/api/staticmap?center=5')"></div>
      </div>
    </div>

    <div class="col-4">
      <div class="flat-show-card">
        <h5>Book this place!</h5>

        <form action="">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">From:</span>
            <input type="text" class="form-control" placeholder="12/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <div class="input-group mt-2">
            <span class="input-group-addon" id="basic-addon1">To:</span>
            <input type="text" class="form-control" placeholder="18/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
        </form>
      </div>
      <div class="flat-show-card">
        <h3>Details</h3>
        <div class="flex">
          <div class="flex">
            <i class="material-icons mr-2">people</i><span><%= @flat.number_of_guests %></span>
          </div>
          <div class="flex ml-3">
            <i class="material-icons mr-2">euro_symbol</i> <%= @flat.price_per_night %>
          </div>
        </div>
      </div>
      <div class="flat-show-card">
        <div class="flex-align">
          <h6 class="no-mb">Share</h6>

          <div class="flex">
            <i class="fa fa-facebook-square fa-2x mr-2"></i>
            <i class="fa fa-twitter-square fa-2x mr-2"></i>
            <i class="fa fa-pinterest-square fa-2x mr-2"></i>
            <i class="fa fa-envelope-square fa-2x"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsSimpleAirbnb</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
</head>

<body>
  <%= render 'navbar' %>
  <%= yield %>
</body>
</html>